insert into workshopinformation (id, name, description, maximumParticipants)
VALUES
(0, 'ActionScript Entry-level', 'Lorem ipsum dolor sit amet.', 15),
(1, 'ActionScript Beginner', 'Lorem ipsum dolor sit amet.', 20),
(2, 'ActionScript Advanced', 'Lorem ipsum dolor sit amet.', 20),
(3, 'ActionScript Master', 'Lorem ipsum dolor sit amet.', 20),
(4, 'ALGOL Entry-level', 'Lorem ipsum dolor sit amet.', 10),
(5, 'ALGOL Beginner', 'Lorem ipsum dolor sit amet.', 20),
(6, 'ALGOL Advanced', 'Lorem ipsum dolor sit amet.', 20),
(7, 'ALGOL Master', 'Lorem ipsum dolor sit amet.', 20),
(8, 'Ada Entry-level', 'Lorem ipsum dolor sit amet.', 20),
(9, 'Ada Beginner', 'Lorem ipsum dolor sit amet.', 20),
(10, 'Ada Advanced', 'Lorem ipsum dolor sit amet.', 15),
(11, 'Ada Master', 'Lorem ipsum dolor sit amet.', 20),
(12, 'AIML Entry-level', 'Lorem ipsum dolor sit amet.', 20),
(13, 'AIML Beginner', 'Lorem ipsum dolor sit amet.', 20),
(14, 'AIML Advanced', 'Lorem ipsum dolor sit amet.', 20),
(15, 'AIML Master', 'Lorem ipsum dolor sit amet.', 15),
(16, 'Altair BASIC Entry-level', 'Lorem ipsum dolor sit amet.', 15),
(17, 'Altair BASIC Beginner', 'Lorem ipsum dolor sit amet.', 15),
(18, 'Altair BASIC Advanced', 'Lorem ipsum dolor sit amet.', 20),
(19, 'Altair BASIC Master', 'Lorem ipsum dolor sit amet.', 10),
(20, 'Assembly Entry-level', 'Lorem ipsum dolor sit amet.', 15),
(21, 'Assembly Beginner', 'Lorem ipsum dolor sit amet.', 20),
(22, 'Assembly Advanced', 'Lorem ipsum dolor sit amet.', 20),
(23, 'Assembly Master', 'Lorem ipsum dolor sit amet.', 10),
(24, 'BASIC Entry-level', 'Lorem ipsum dolor sit amet.', 10),
(25, 'BASIC Beginner', 'Lorem ipsum dolor sit amet.', 15),
(26, 'BASIC Advanced', 'Lorem ipsum dolor sit amet.', 20),
(27, 'BASIC Master', 'Lorem ipsum dolor sit amet.', 20),
(28, 'BeanShell Entry-level', 'Lorem ipsum dolor sit amet.', 15),
(29, 'BeanShell Beginner', 'Lorem ipsum dolor sit amet.', 20),
(30, 'BeanShell Advanced', 'Lorem ipsum dolor sit amet.', 15),
(31, 'BeanShell Master', 'Lorem ipsum dolor sit amet.', 10),
(32, 'Bug Entry-level', 'Lorem ipsum dolor sit amet.', 10),
(33, 'Bug Beginner', 'Lorem ipsum dolor sit amet.', 15),
(34, 'Bug Advanced', 'Lorem ipsum dolor sit amet.', 15),
(35, 'Bug Master', 'Lorem ipsum dolor sit amet.', 10),
(36, 'C Entry-level', 'Lorem ipsum dolor sit amet.', 10),
(37, 'C Beginner', 'Lorem ipsum dolor sit amet.', 15),
(38, 'C Advanced', 'Lorem ipsum dolor sit amet.', 15),
(39, 'C Master', 'Lorem ipsum dolor sit amet.', 10),
(40, 'C# Entry-level', 'Lorem ipsum dolor sit amet.', 20),
(41, 'C# Beginner', 'Lorem ipsum dolor sit amet.', 10),
(42, 'C# Advanced', 'Lorem ipsum dolor sit amet.', 10),
(43, 'C# Master', 'Lorem ipsum dolor sit amet.', 15),
(44, 'C++ Entry-level', 'Lorem ipsum dolor sit amet.', 15),
(45, 'C++ Beginner', 'Lorem ipsum dolor sit amet.', 15),
(46, 'C++ Advanced', 'Lorem ipsum dolor sit amet.', 20),
(47, 'C++ Master', 'Lorem ipsum dolor sit amet.', 15),
(48, 'Clojure Entry-level', 'Lorem ipsum dolor sit amet.', 10),
(49, 'Clojure Beginner', 'Lorem ipsum dolor sit amet.', 20),
(50, 'Clojure Advanced', 'Lorem ipsum dolor sit amet.', 15),
(51, 'Clojure Master', 'Lorem ipsum dolor sit amet.', 20),
(52, 'COBOL Entry-level', 'Lorem ipsum dolor sit amet.', 10),
(53, 'COBOL Beginner', 'Lorem ipsum dolor sit amet.', 10),
(54, 'COBOL Advanced', 'Lorem ipsum dolor sit amet.', 20),
(55, 'COBOL Master', 'Lorem ipsum dolor sit amet.', 20),
(56, 'CoffeeScript Entry-level', 'Lorem ipsum dolor sit amet.', 10),
(57, 'CoffeeScript Beginner', 'Lorem ipsum dolor sit amet.', 15),
(58, 'CoffeeScript Advanced', 'Lorem ipsum dolor sit amet.', 10),
(59, 'CoffeeScript Master', 'Lorem ipsum dolor sit amet.', 10),
(60, 'Common Lisp Entry-level', 'Lorem ipsum dolor sit amet.', 20),
(61, 'Common Lisp Beginner', 'Lorem ipsum dolor sit amet.', 10),
(62, 'Common Lisp Advanced', 'Lorem ipsum dolor sit amet.', 10),
(63, 'Common Lisp Master', 'Lorem ipsum dolor sit amet.', 15),
(64, 'CPL Entry-level', 'Lorem ipsum dolor sit amet.', 10),
(65, 'CPL Beginner', 'Lorem ipsum dolor sit amet.', 10),
(66, 'CPL Advanced', 'Lorem ipsum dolor sit amet.', 20),
(67, 'CPL Master', 'Lorem ipsum dolor sit amet.', 10),
(68, 'CSS Entry-level', 'Lorem ipsum dolor sit amet.', 15),
(69, 'CSS Beginner', 'Lorem ipsum dolor sit amet.', 20),
(70, 'CSS Advanced', 'Lorem ipsum dolor sit amet.', 10),
(71, 'CSS Master', 'Lorem ipsum dolor sit amet.', 20),
(72, 'Curl Entry-level', 'Lorem ipsum dolor sit amet.', 20),
(73, 'Curl Beginner', 'Lorem ipsum dolor sit amet.', 20),
(74, 'Curl Advanced', 'Lorem ipsum dolor sit amet.', 15),
(75, 'Curl Master', 'Lorem ipsum dolor sit amet.', 10),
(76, 'Curry Entry-level', 'Lorem ipsum dolor sit amet.', 15),
(77, 'Curry Beginner', 'Lorem ipsum dolor sit amet.', 15),
(78, 'Curry Advanced', 'Lorem ipsum dolor sit amet.', 10),
(79, 'Curry Master', 'Lorem ipsum dolor sit amet.', 15),
(80, 'DarkBASIC Entry-level', 'Lorem ipsum dolor sit amet.', 20),
(81, 'DarkBASIC Beginner', 'Lorem ipsum dolor sit amet.', 20),
(82, 'DarkBASIC Advanced', 'Lorem ipsum dolor sit amet.', 10),
(83, 'DarkBASIC Master', 'Lorem ipsum dolor sit amet.', 10),
(84, 'Dart Entry-level', 'Lorem ipsum dolor sit amet.', 15),
(85, 'Dart Beginner', 'Lorem ipsum dolor sit amet.', 15),
(86, 'Dart Advanced', 'Lorem ipsum dolor sit amet.', 10),
(87, 'Dart Master', 'Lorem ipsum dolor sit amet.', 10),
(88, 'Databases Entry-level', 'Lorem ipsum dolor sit amet.', 10),
(89, 'Databases Beginner', 'Lorem ipsum dolor sit amet.', 20),
(90, 'Databases Advanced', 'Lorem ipsum dolor sit amet.', 20),
(91, 'Databases Master', 'Lorem ipsum dolor sit amet.', 20),
(92, 'Debug Entry-level', 'Lorem ipsum dolor sit amet.', 10),
(93, 'Debug Beginner', 'Lorem ipsum dolor sit amet.', 15),
(94, 'Debug Advanced', 'Lorem ipsum dolor sit amet.', 10),
(95, 'Debug Master', 'Lorem ipsum dolor sit amet.', 20),
(96, 'Dylan Entry-level', 'Lorem ipsum dolor sit amet.', 20),
(97, 'Dylan Beginner', 'Lorem ipsum dolor sit amet.', 20),
(98, 'Dylan Advanced', 'Lorem ipsum dolor sit amet.', 15),
(99, 'Dylan Master', 'Lorem ipsum dolor sit amet.', 20),
(100, 'EuLisp Entry-level', 'Lorem ipsum dolor sit amet.', 15),
(101, 'EuLisp Beginner', 'Lorem ipsum dolor sit amet.', 10),
(102, 'EuLisp Advanced', 'Lorem ipsum dolor sit amet.', 15),
(103, 'EuLisp Master', 'Lorem ipsum dolor sit amet.', 15),
(104, 'F Entry-level', 'Lorem ipsum dolor sit amet.', 20),
(105, 'F Beginner', 'Lorem ipsum dolor sit amet.', 10),
(106, 'F Advanced', 'Lorem ipsum dolor sit amet.', 10),
(107, 'F Master', 'Lorem ipsum dolor sit amet.', 15),
(108, 'F# Entry-level', 'Lorem ipsum dolor sit amet.', 20),
(109, 'F# Beginner', 'Lorem ipsum dolor sit amet.', 10),
(110, 'F# Advanced', 'Lorem ipsum dolor sit amet.', 10),
(111, 'F# Master', 'Lorem ipsum dolor sit amet.', 15),
(112, 'FORTRAN Entry-level', 'Lorem ipsum dolor sit amet.', 20),
(113, 'FORTRAN Beginner', 'Lorem ipsum dolor sit amet.', 20),
(114, 'FORTRAN Advanced', 'Lorem ipsum dolor sit amet.', 20),
(115, 'FORTRAN Master', 'Lorem ipsum dolor sit amet.', 10),
(116, 'FoxPro Entry-level', 'Lorem ipsum dolor sit amet.', 10),
(117, 'FoxPro Beginner', 'Lorem ipsum dolor sit amet.', 20),
(118, 'FoxPro Advanced', 'Lorem ipsum dolor sit amet.', 10),
(119, 'FoxPro Master', 'Lorem ipsum dolor sit amet.', 15),
(120, 'Go Entry-level', 'Lorem ipsum dolor sit amet.', 20),
(121, 'Go Beginner', 'Lorem ipsum dolor sit amet.', 10),
(122, 'Go Advanced', 'Lorem ipsum dolor sit amet.', 20),
(123, 'Go Master', 'Lorem ipsum dolor sit amet.', 20),
(124, 'Haskell Entry-level', 'Lorem ipsum dolor sit amet.', 10),
(125, 'Haskell Beginner', 'Lorem ipsum dolor sit amet.', 10),
(126, 'Haskell Advanced', 'Lorem ipsum dolor sit amet.', 15),
(127, 'Haskell Master', 'Lorem ipsum dolor sit amet.', 10),
(128, 'HDML Entry-level', 'Lorem ipsum dolor sit amet.', 20),
(129, 'HDML Beginner', 'Lorem ipsum dolor sit amet.', 15),
(130, 'HDML Advanced', 'Lorem ipsum dolor sit amet.', 15),
(131, 'HDML Master', 'Lorem ipsum dolor sit amet.', 10),
(132, 'HTML Entry-level', 'Lorem ipsum dolor sit amet.', 15),
(133, 'HTML Beginner', 'Lorem ipsum dolor sit amet.', 20),
(134, 'HTML Advanced', 'Lorem ipsum dolor sit amet.', 20),
(135, 'HTML Master', 'Lorem ipsum dolor sit amet.', 15),
(136, 'InterLisp Entry-level', 'Lorem ipsum dolor sit amet.', 20),
(137, 'InterLisp Beginner', 'Lorem ipsum dolor sit amet.', 10),
(138, 'InterLisp Advanced', 'Lorem ipsum dolor sit amet.', 15),
(139, 'InterLisp Master', 'Lorem ipsum dolor sit amet.', 20),
(140, 'Java Entry-level', 'Lorem ipsum dolor sit amet.', 20),
(141, 'Java Beginner', 'Lorem ipsum dolor sit amet.', 10),
(142, 'Java Advanced', 'Lorem ipsum dolor sit amet.', 15),
(143, 'Java Master', 'Lorem ipsum dolor sit amet.', 15),
(144, 'JavaScript Entry-level', 'Lorem ipsum dolor sit amet.', 15),
(145, 'JavaScript Beginner', 'Lorem ipsum dolor sit amet.', 10),
(146, 'JavaScript Advanced', 'Lorem ipsum dolor sit amet.', 10),
(147, 'JavaScript Master', 'Lorem ipsum dolor sit amet.', 20),
(148, 'Julia Entry-level', 'Lorem ipsum dolor sit amet.', 10),
(149, 'Julia Beginner', 'Lorem ipsum dolor sit amet.', 20),
(150, 'Julia Advanced', 'Lorem ipsum dolor sit amet.', 20),
(151, 'Julia Master', 'Lorem ipsum dolor sit amet.', 20),
(152, 'Lisp Entry-level', 'Lorem ipsum dolor sit amet.', 20),
(153, 'Lisp Beginner', 'Lorem ipsum dolor sit amet.', 10),
(154, 'Lisp Advanced', 'Lorem ipsum dolor sit amet.', 15),
(155, 'Lisp Master', 'Lorem ipsum dolor sit amet.', 10),
(156, 'LiveScript Entry-level', 'Lorem ipsum dolor sit amet.', 20),
(157, 'LiveScript Beginner', 'Lorem ipsum dolor sit amet.', 10),
(158, 'LiveScript Advanced', 'Lorem ipsum dolor sit amet.', 20),
(159, 'LiveScript Master', 'Lorem ipsum dolor sit amet.', 15),
(160, 'LOGO Entry-level', 'Lorem ipsum dolor sit amet.', 15),
(161, 'LOGO Beginner', 'Lorem ipsum dolor sit amet.', 10),
(162, 'LOGO Advanced', 'Lorem ipsum dolor sit amet.', 20),
(163, 'LOGO Master', 'Lorem ipsum dolor sit amet.', 15),
(164, 'Lua Entry-level', 'Lorem ipsum dolor sit amet.', 15),
(165, 'Lua Beginner', 'Lorem ipsum dolor sit amet.', 15),
(166, 'Lua Advanced', 'Lorem ipsum dolor sit amet.', 10),
(167, 'Lua Master', 'Lorem ipsum dolor sit amet.', 15),
(168, 'MACLISP Entry-level', 'Lorem ipsum dolor sit amet.', 20),
(169, 'MACLISP Beginner', 'Lorem ipsum dolor sit amet.', 10),
(170, 'MACLISP Advanced', 'Lorem ipsum dolor sit amet.', 20),
(171, 'MACLISP Master', 'Lorem ipsum dolor sit amet.', 20),
(172, 'Matlab Entry-level', 'Lorem ipsum dolor sit amet.', 10),
(173, 'Matlab Beginner', 'Lorem ipsum dolor sit amet.', 15),
(174, 'Matlab Advanced', 'Lorem ipsum dolor sit amet.', 15),
(175, 'Matlab Master', 'Lorem ipsum dolor sit amet.', 20),
(176, 'MUMPS Entry-level', 'Lorem ipsum dolor sit amet.', 10),
(177, 'MUMPS Beginner', 'Lorem ipsum dolor sit amet.', 20),
(178, 'MUMPS Advanced', 'Lorem ipsum dolor sit amet.', 20),
(179, 'MUMPS Master', 'Lorem ipsum dolor sit amet.', 10),
(180, 'Objective-C Entry-level', 'Lorem ipsum dolor sit amet.', 15),
(181, 'Objective-C Beginner', 'Lorem ipsum dolor sit amet.', 20),
(182, 'Objective-C Advanced', 'Lorem ipsum dolor sit amet.', 20),
(183, 'Objective-C Master', 'Lorem ipsum dolor sit amet.', 15),
(184, 'OCaml Entry-level', 'Lorem ipsum dolor sit amet.', 10),
(185, 'OCaml Beginner', 'Lorem ipsum dolor sit amet.', 10),
(186, 'OCaml Advanced', 'Lorem ipsum dolor sit amet.', 15),
(187, 'OCaml Master', 'Lorem ipsum dolor sit amet.', 15),
(188, 'Pascal Entry-level', 'Lorem ipsum dolor sit amet.', 20),
(189, 'Pascal Beginner', 'Lorem ipsum dolor sit amet.', 15),
(190, 'Pascal Advanced', 'Lorem ipsum dolor sit amet.', 15),
(191, 'Pascal Master', 'Lorem ipsum dolor sit amet.', 10),
(192, 'Perl Entry-level', 'Lorem ipsum dolor sit amet.', 20),
(193, 'Perl Beginner', 'Lorem ipsum dolor sit amet.', 20),
(194, 'Perl Advanced', 'Lorem ipsum dolor sit amet.', 15),
(195, 'Perl Master', 'Lorem ipsum dolor sit amet.', 10),
(196, 'PHP Entry-level', 'Lorem ipsum dolor sit amet.', 15),
(197, 'PHP Beginner', 'Lorem ipsum dolor sit amet.', 20),
(198, 'PHP Advanced', 'Lorem ipsum dolor sit amet.', 20),
(199, 'PHP Master', 'Lorem ipsum dolor sit amet.', 10),
(200, 'PureBasic Entry-level', 'Lorem ipsum dolor sit amet.', 10),
(201, 'PureBasic Beginner', 'Lorem ipsum dolor sit amet.', 10),
(202, 'PureBasic Advanced', 'Lorem ipsum dolor sit amet.', 15),
(203, 'PureBasic Master', 'Lorem ipsum dolor sit amet.', 20),
(204, 'Python Entry-level', 'Lorem ipsum dolor sit amet.', 15),
(205, 'Python Beginner', 'Lorem ipsum dolor sit amet.', 15),
(206, 'Python Advanced', 'Lorem ipsum dolor sit amet.', 10),
(207, 'Python Master', 'Lorem ipsum dolor sit amet.', 20),
(208, 'Prolog Entry-level', 'Lorem ipsum dolor sit amet.', 20),
(209, 'Prolog Beginner', 'Lorem ipsum dolor sit amet.', 20),
(210, 'Prolog Advanced', 'Lorem ipsum dolor sit amet.', 20),
(211, 'Prolog Master', 'Lorem ipsum dolor sit amet.', 15),
(212, 'QBasic Entry-level', 'Lorem ipsum dolor sit amet.', 20),
(213, 'QBasic Beginner', 'Lorem ipsum dolor sit amet.', 10),
(214, 'QBasic Advanced', 'Lorem ipsum dolor sit amet.', 10),
(215, 'QBasic Master', 'Lorem ipsum dolor sit amet.', 10),
(216, 'R Entry-level', 'Lorem ipsum dolor sit amet.', 15),
(217, 'R Beginner', 'Lorem ipsum dolor sit amet.', 15),
(218, 'R Advanced', 'Lorem ipsum dolor sit amet.', 10),
(219, 'R Master', 'Lorem ipsum dolor sit amet.', 20),
(220, 'Reia Entry-level', 'Lorem ipsum dolor sit amet.', 15),
(221, 'Reia Beginner', 'Lorem ipsum dolor sit amet.', 10),
(222, 'Reia Advanced', 'Lorem ipsum dolor sit amet.', 10),
(223, 'Reia Master', 'Lorem ipsum dolor sit amet.', 15),
(224, 'Ruby Entry-level', 'Lorem ipsum dolor sit amet.', 10),
(225, 'Ruby Beginner', 'Lorem ipsum dolor sit amet.', 10),
(226, 'Ruby Advanced', 'Lorem ipsum dolor sit amet.', 20),
(227, 'Ruby Master', 'Lorem ipsum dolor sit amet.', 15),
(228, 'Rust Entry-level', 'Lorem ipsum dolor sit amet.', 10),
(229, 'Rust Beginner', 'Lorem ipsum dolor sit amet.', 20),
(230, 'Rust Advanced', 'Lorem ipsum dolor sit amet.', 10),
(231, 'Rust Master', 'Lorem ipsum dolor sit amet.', 20),
(232, 'Scala Entry-level', 'Lorem ipsum dolor sit amet.', 15),
(233, 'Scala Beginner', 'Lorem ipsum dolor sit amet.', 10),
(234, 'Scala Advanced', 'Lorem ipsum dolor sit amet.', 10),
(235, 'Scala Master', 'Lorem ipsum dolor sit amet.', 10),
(236, 'Security Entry-level', 'Lorem ipsum dolor sit amet.', 10),
(237, 'Security Beginner', 'Lorem ipsum dolor sit amet.', 20),
(238, 'Security Advanced', 'Lorem ipsum dolor sit amet.', 15),
(239, 'Security Master', 'Lorem ipsum dolor sit amet.', 10),
(240, 'SGML Entry-level', 'Lorem ipsum dolor sit amet.', 10),
(241, 'SGML Beginner', 'Lorem ipsum dolor sit amet.', 15),
(242, 'SGML Advanced', 'Lorem ipsum dolor sit amet.', 20),
(243, 'SGML Master', 'Lorem ipsum dolor sit amet.', 15),
(244, 'Simula Entry-level', 'Lorem ipsum dolor sit amet.', 20),
(245, 'Simula Beginner', 'Lorem ipsum dolor sit amet.', 20),
(246, 'Simula Advanced', 'Lorem ipsum dolor sit amet.', 20),
(247, 'Simula Master', 'Lorem ipsum dolor sit amet.', 15),
(248, 'SQL Entry-level', 'Lorem ipsum dolor sit amet.', 20),
(249, 'SQL Beginner', 'Lorem ipsum dolor sit amet.', 20),
(250, 'SQL Advanced', 'Lorem ipsum dolor sit amet.', 15),
(251, 'SQL Master', 'Lorem ipsum dolor sit amet.', 20),
(252, 'SQL injection Entry-level', 'Lorem ipsum dolor sit amet.', 10),
(253, 'SQL injection Beginner', 'Lorem ipsum dolor sit amet.', 15),
(254, 'SQL injection Advanced', 'Lorem ipsum dolor sit amet.', 20),
(255, 'SQL injection Master', 'Lorem ipsum dolor sit amet.', 20),
(256, 'StackOverflow Entry-level', 'Lorem ipsum dolor sit amet.', 10),
(257, 'StackOverflow Beginner', 'Lorem ipsum dolor sit amet.', 20),
(258, 'StackOverflow Advanced', 'Lorem ipsum dolor sit amet.', 20),
(259, 'StackOverflow Master', 'Lorem ipsum dolor sit amet.', 20),
(260, 'Stanford LISP Entry-level', 'Lorem ipsum dolor sit amet.', 20),
(261, 'Stanford LISP Beginner', 'Lorem ipsum dolor sit amet.', 20),
(262, 'Stanford LISP Advanced', 'Lorem ipsum dolor sit amet.', 15),
(263, 'Stanford LISP Master', 'Lorem ipsum dolor sit amet.', 15),
(264, 'Swift Entry-level', 'Lorem ipsum dolor sit amet.', 15),
(265, 'Swift Beginner', 'Lorem ipsum dolor sit amet.', 15),
(266, 'Swift Advanced', 'Lorem ipsum dolor sit amet.', 20),
(267, 'Swift Master', 'Lorem ipsum dolor sit amet.', 20),
(268, 'Turbo Pascal Entry-level', 'Lorem ipsum dolor sit amet.', 20),
(269, 'Turbo Pascal Beginner', 'Lorem ipsum dolor sit amet.', 20),
(270, 'Turbo Pascal Advanced', 'Lorem ipsum dolor sit amet.', 15),
(271, 'Turbo Pascal Master', 'Lorem ipsum dolor sit amet.', 20),
(272, 'True BASIC Entry-level', 'Lorem ipsum dolor sit amet.', 20),
(273, 'True BASIC Beginner', 'Lorem ipsum dolor sit amet.', 10),
(274, 'True BASIC Advanced', 'Lorem ipsum dolor sit amet.', 20),
(275, 'True BASIC Master', 'Lorem ipsum dolor sit amet.', 10),
(276, 'VHDL Entry-level', 'Lorem ipsum dolor sit amet.', 20),
(277, 'VHDL Beginner', 'Lorem ipsum dolor sit amet.', 15),
(278, 'VHDL Advanced', 'Lorem ipsum dolor sit amet.', 20),
(279, 'VHDL Master', 'Lorem ipsum dolor sit amet.', 15),
(280, 'Visual Basic Entry-level', 'Lorem ipsum dolor sit amet.', 20),
(281, 'Visual Basic Beginner', 'Lorem ipsum dolor sit amet.', 15),
(282, 'Visual Basic Advanced', 'Lorem ipsum dolor sit amet.', 20),
(283, 'Visual Basic Master', 'Lorem ipsum dolor sit amet.', 10),
(284, 'Visual FoxPro Entry-level', 'Lorem ipsum dolor sit amet.', 15),
(285, 'Visual FoxPro Beginner', 'Lorem ipsum dolor sit amet.', 15),
(286, 'Visual FoxPro Advanced', 'Lorem ipsum dolor sit amet.', 10),
(287, 'Visual FoxPro Master', 'Lorem ipsum dolor sit amet.', 15),
(288, 'WML Entry-level', 'Lorem ipsum dolor sit amet.', 10),
(289, 'WML Beginner', 'Lorem ipsum dolor sit amet.', 20),
(290, 'WML Advanced', 'Lorem ipsum dolor sit amet.', 15),
(291, 'WML Master', 'Lorem ipsum dolor sit amet.', 15),
(292, 'WHTML Entry-level', 'Lorem ipsum dolor sit amet.', 10),
(293, 'WHTML Beginner', 'Lorem ipsum dolor sit amet.', 10),
(294, 'WHTML Advanced', 'Lorem ipsum dolor sit amet.', 15),
(295, 'WHTML Master', 'Lorem ipsum dolor sit amet.', 15),
(296, 'XLISP Entry-level', 'Lorem ipsum dolor sit amet.', 15),
(297, 'XLISP Beginner', 'Lorem ipsum dolor sit amet.', 20),
(298, 'XLISP Advanced', 'Lorem ipsum dolor sit amet.', 15),
(299, 'XLISP Master', 'Lorem ipsum dolor sit amet.', 15),
(300, 'XML Entry-level', 'Lorem ipsum dolor sit amet.', 10),
(301, 'XML Beginner', 'Lorem ipsum dolor sit amet.', 15),
(302, 'XML Advanced', 'Lorem ipsum dolor sit amet.', 15),
(303, 'XML Master', 'Lorem ipsum dolor sit amet.', 10),
(304, 'XSS Entry-level', 'Lorem ipsum dolor sit amet.', 10),
(305, 'XSS Beginner', 'Lorem ipsum dolor sit amet.', 15),
(306, 'XSS Advanced', 'Lorem ipsum dolor sit amet.', 10),
(307, 'XSS Master', 'Lorem ipsum dolor sit amet.', 20),
(308, 'YAML Entry-level', 'Lorem ipsum dolor sit amet.', 10),
(309, 'YAML Beginner', 'Lorem ipsum dolor sit amet.', 10),
(310, 'YAML Advanced', 'Lorem ipsum dolor sit amet.', 10),
(311, 'YAML Master', 'Lorem ipsum dolor sit amet.', 20),
(312, 'ZetaLisp Entry-level', 'Lorem ipsum dolor sit amet.', 15),
(313, 'ZetaLisp Beginner', 'Lorem ipsum dolor sit amet.', 20),
(314, 'ZetaLisp Advanced', 'Lorem ipsum dolor sit amet.', 20),
(315, 'ZetaLisp Master', 'Lorem ipsum dolor sit amet.', 20);
