INSERT INTO Workshopinformation (name, description, maximumParticipants)
VALUES
( 'ActionScript Entry-level', 'Lorem ipsum dolor sit amet.', 20),
( 'ActionScript Beginner', 'Lorem ipsum dolor sit amet.', 15),
( 'ActionScript Advanced', 'Lorem ipsum dolor sit amet.', 15),
( 'ActionScript Master', 'Lorem ipsum dolor sit amet.', 15),
( 'ALGOL Entry-level', 'Lorem ipsum dolor sit amet.', 10),
( 'ALGOL Beginner', 'Lorem ipsum dolor sit amet.', 10),
( 'ALGOL Advanced', 'Lorem ipsum dolor sit amet.', 20),
( 'ALGOL Master', 'Lorem ipsum dolor sit amet.', 20),
( 'Ada Entry-level', 'Lorem ipsum dolor sit amet.', 20),
( 'Ada Beginner', 'Lorem ipsum dolor sit amet.', 10),
( 'Ada Advanced', 'Lorem ipsum dolor sit amet.', 20),
( 'Ada Master', 'Lorem ipsum dolor sit amet.', 15),
( 'AIML Entry-level', 'Lorem ipsum dolor sit amet.', 10),
( 'AIML Beginner', 'Lorem ipsum dolor sit amet.', 20),
( 'AIML Advanced', 'Lorem ipsum dolor sit amet.', 15),
( 'AIML Master', 'Lorem ipsum dolor sit amet.', 10),
( 'Altair BASIC Entry-level', 'Lorem ipsum dolor sit amet.', 10),
( 'Altair BASIC Beginner', 'Lorem ipsum dolor sit amet.', 20),
( 'Altair BASIC Advanced', 'Lorem ipsum dolor sit amet.', 15),
( 'Altair BASIC Master', 'Lorem ipsum dolor sit amet.', 20),
( 'Assembly Entry-level', 'Lorem ipsum dolor sit amet.', 20),
( 'Assembly Beginner', 'Lorem ipsum dolor sit amet.', 10),
( 'Assembly Advanced', 'Lorem ipsum dolor sit amet.', 20),
( 'Assembly Master', 'Lorem ipsum dolor sit amet.', 20),
( 'BASIC Entry-level', 'Lorem ipsum dolor sit amet.', 15),
( 'BASIC Beginner', 'Lorem ipsum dolor sit amet.', 10),
( 'BASIC Advanced', 'Lorem ipsum dolor sit amet.', 15),
( 'BASIC Master', 'Lorem ipsum dolor sit amet.', 10),
( 'BeanShell Entry-level', 'Lorem ipsum dolor sit amet.', 15),
( 'BeanShell Beginner', 'Lorem ipsum dolor sit amet.', 10),
( 'BeanShell Advanced', 'Lorem ipsum dolor sit amet.', 15),
( 'BeanShell Master', 'Lorem ipsum dolor sit amet.', 10),
( 'Bug Entry-level', 'Lorem ipsum dolor sit amet.', 20),
( 'Bug Beginner', 'Lorem ipsum dolor sit amet.', 20),
( 'Bug Advanced', 'Lorem ipsum dolor sit amet.', 20),
( 'Bug Master', 'Lorem ipsum dolor sit amet.', 20),
( 'C Entry-level', 'Lorem ipsum dolor sit amet.', 15),
( 'C Beginner', 'Lorem ipsum dolor sit amet.', 10),
( 'C Advanced', 'Lorem ipsum dolor sit amet.', 20),
( 'C Master', 'Lorem ipsum dolor sit amet.', 10),
( 'C# Entry-level', 'Lorem ipsum dolor sit amet.', 20),
( 'C# Beginner', 'Lorem ipsum dolor sit amet.', 10),
( 'C# Advanced', 'Lorem ipsum dolor sit amet.', 10),
( 'C# Master', 'Lorem ipsum dolor sit amet.', 10),
( 'C++ Entry-level', 'Lorem ipsum dolor sit amet.', 15),
( 'C++ Beginner', 'Lorem ipsum dolor sit amet.', 10),
( 'C++ Advanced', 'Lorem ipsum dolor sit amet.', 15),
( 'C++ Master', 'Lorem ipsum dolor sit amet.', 15),
( 'Clojure Entry-level', 'Lorem ipsum dolor sit amet.', 20),
( 'Clojure Beginner', 'Lorem ipsum dolor sit amet.', 10),
( 'Clojure Advanced', 'Lorem ipsum dolor sit amet.', 15),
( 'Clojure Master', 'Lorem ipsum dolor sit amet.', 15),
( 'COBOL Entry-level', 'Lorem ipsum dolor sit amet.', 15),
( 'COBOL Beginner', 'Lorem ipsum dolor sit amet.', 10),
( 'COBOL Advanced', 'Lorem ipsum dolor sit amet.', 15),
( 'COBOL Master', 'Lorem ipsum dolor sit amet.', 20),
( 'CoffeeScript Entry-level', 'Lorem ipsum dolor sit amet.', 10),
( 'CoffeeScript Beginner', 'Lorem ipsum dolor sit amet.', 10),
( 'CoffeeScript Advanced', 'Lorem ipsum dolor sit amet.', 20),
( 'CoffeeScript Master', 'Lorem ipsum dolor sit amet.', 15),
( 'Common Lisp Entry-level', 'Lorem ipsum dolor sit amet.', 20),
( 'Common Lisp Beginner', 'Lorem ipsum dolor sit amet.', 20),
( 'Common Lisp Advanced', 'Lorem ipsum dolor sit amet.', 15),
( 'Common Lisp Master', 'Lorem ipsum dolor sit amet.', 20),
( 'CPL Entry-level', 'Lorem ipsum dolor sit amet.', 15),
( 'CPL Beginner', 'Lorem ipsum dolor sit amet.', 20),
( 'CPL Advanced', 'Lorem ipsum dolor sit amet.', 20),
( 'CPL Master', 'Lorem ipsum dolor sit amet.', 20),
( 'CSS Entry-level', 'Lorem ipsum dolor sit amet.', 20),
( 'CSS Beginner', 'Lorem ipsum dolor sit amet.', 20),
( 'CSS Advanced', 'Lorem ipsum dolor sit amet.', 10),
( 'CSS Master', 'Lorem ipsum dolor sit amet.', 10),
( 'Curl Entry-level', 'Lorem ipsum dolor sit amet.', 10),
( 'Curl Beginner', 'Lorem ipsum dolor sit amet.', 10),
( 'Curl Advanced', 'Lorem ipsum dolor sit amet.', 20),
( 'Curl Master', 'Lorem ipsum dolor sit amet.', 10),
( 'Curry Entry-level', 'Lorem ipsum dolor sit amet.', 20),
( 'Curry Beginner', 'Lorem ipsum dolor sit amet.', 10),
( 'Curry Advanced', 'Lorem ipsum dolor sit amet.', 15),
( 'Curry Master', 'Lorem ipsum dolor sit amet.', 15),
( 'DarkBASIC Entry-level', 'Lorem ipsum dolor sit amet.', 20),
( 'DarkBASIC Beginner', 'Lorem ipsum dolor sit amet.', 15),
( 'DarkBASIC Advanced', 'Lorem ipsum dolor sit amet.', 15),
( 'DarkBASIC Master', 'Lorem ipsum dolor sit amet.', 10),
( 'Dart Entry-level', 'Lorem ipsum dolor sit amet.', 10),
( 'Dart Beginner', 'Lorem ipsum dolor sit amet.', 10),
( 'Dart Advanced', 'Lorem ipsum dolor sit amet.', 10),
( 'Dart Master', 'Lorem ipsum dolor sit amet.', 10),
( 'Databases Entry-level', 'Lorem ipsum dolor sit amet.', 15),
( 'Databases Beginner', 'Lorem ipsum dolor sit amet.', 15),
( 'Databases Advanced', 'Lorem ipsum dolor sit amet.', 15),
( 'Databases Master', 'Lorem ipsum dolor sit amet.', 10),
( 'Debug Entry-level', 'Lorem ipsum dolor sit amet.', 15),
( 'Debug Beginner', 'Lorem ipsum dolor sit amet.', 10),
( 'Debug Advanced', 'Lorem ipsum dolor sit amet.', 20),
( 'Debug Master', 'Lorem ipsum dolor sit amet.', 15),
( 'Dylan Entry-level', 'Lorem ipsum dolor sit amet.', 20),
( 'Dylan Beginner', 'Lorem ipsum dolor sit amet.', 20),
( 'Dylan Advanced', 'Lorem ipsum dolor sit amet.', 15),
( 'Dylan Master', 'Lorem ipsum dolor sit amet.', 20),
( 'EuLisp Entry-level', 'Lorem ipsum dolor sit amet.', 10),
( 'EuLisp Beginner', 'Lorem ipsum dolor sit amet.', 15),
( 'EuLisp Advanced', 'Lorem ipsum dolor sit amet.', 15),
( 'EuLisp Master', 'Lorem ipsum dolor sit amet.', 20),
( 'F Entry-level', 'Lorem ipsum dolor sit amet.', 15),
( 'F Beginner', 'Lorem ipsum dolor sit amet.', 15),
( 'F Advanced', 'Lorem ipsum dolor sit amet.', 15),
( 'F Master', 'Lorem ipsum dolor sit amet.', 15),
( 'F# Entry-level', 'Lorem ipsum dolor sit amet.', 10),
( 'F# Beginner', 'Lorem ipsum dolor sit amet.', 15),
( 'F# Advanced', 'Lorem ipsum dolor sit amet.', 20),
( 'F# Master', 'Lorem ipsum dolor sit amet.', 10),
( 'FORTRAN Entry-level', 'Lorem ipsum dolor sit amet.', 15),
( 'FORTRAN Beginner', 'Lorem ipsum dolor sit amet.', 10),
( 'FORTRAN Advanced', 'Lorem ipsum dolor sit amet.', 15),
( 'FORTRAN Master', 'Lorem ipsum dolor sit amet.', 10),
( 'FoxPro Entry-level', 'Lorem ipsum dolor sit amet.', 15),
( 'FoxPro Beginner', 'Lorem ipsum dolor sit amet.', 10),
( 'FoxPro Advanced', 'Lorem ipsum dolor sit amet.', 10),
( 'FoxPro Master', 'Lorem ipsum dolor sit amet.', 10),
( 'Go Entry-level', 'Lorem ipsum dolor sit amet.', 10),
( 'Go Beginner', 'Lorem ipsum dolor sit amet.', 15),
( 'Go Advanced', 'Lorem ipsum dolor sit amet.', 10),
( 'Go Master', 'Lorem ipsum dolor sit amet.', 15),
( 'Haskell Entry-level', 'Lorem ipsum dolor sit amet.', 10),
( 'Haskell Beginner', 'Lorem ipsum dolor sit amet.', 10),
( 'Haskell Advanced', 'Lorem ipsum dolor sit amet.', 10),
( 'Haskell Master', 'Lorem ipsum dolor sit amet.', 10),
( 'HDML Entry-level', 'Lorem ipsum dolor sit amet.', 20),
( 'HDML Beginner', 'Lorem ipsum dolor sit amet.', 20),
( 'HDML Advanced', 'Lorem ipsum dolor sit amet.', 15),
( 'HDML Master', 'Lorem ipsum dolor sit amet.', 10),
( 'HTML Entry-level', 'Lorem ipsum dolor sit amet.', 10),
( 'HTML Beginner', 'Lorem ipsum dolor sit amet.', 20),
( 'HTML Advanced', 'Lorem ipsum dolor sit amet.', 20),
( 'HTML Master', 'Lorem ipsum dolor sit amet.', 10),
( 'InterLisp Entry-level', 'Lorem ipsum dolor sit amet.', 10),
( 'InterLisp Beginner', 'Lorem ipsum dolor sit amet.', 20),
( 'InterLisp Advanced', 'Lorem ipsum dolor sit amet.', 20),
( 'InterLisp Master', 'Lorem ipsum dolor sit amet.', 10),
( 'Java Entry-level', 'Lorem ipsum dolor sit amet.', 10),
( 'Java Beginner', 'Lorem ipsum dolor sit amet.', 10),
( 'Java Advanced', 'Lorem ipsum dolor sit amet.', 15),
( 'Java Master', 'Lorem ipsum dolor sit amet.', 15),
( 'JavaScript Entry-level', 'Lorem ipsum dolor sit amet.', 20),
( 'JavaScript Beginner', 'Lorem ipsum dolor sit amet.', 20),
( 'JavaScript Advanced', 'Lorem ipsum dolor sit amet.', 20),
( 'JavaScript Master', 'Lorem ipsum dolor sit amet.', 20),
( 'Julia Entry-level', 'Lorem ipsum dolor sit amet.', 15),
( 'Julia Beginner', 'Lorem ipsum dolor sit amet.', 20),
( 'Julia Advanced', 'Lorem ipsum dolor sit amet.', 15),
( 'Julia Master', 'Lorem ipsum dolor sit amet.', 10),
( 'Lisp Entry-level', 'Lorem ipsum dolor sit amet.', 15),
( 'Lisp Beginner', 'Lorem ipsum dolor sit amet.', 15),
( 'Lisp Advanced', 'Lorem ipsum dolor sit amet.', 15),
( 'Lisp Master', 'Lorem ipsum dolor sit amet.', 10),
( 'LiveScript Entry-level', 'Lorem ipsum dolor sit amet.', 20),
( 'LiveScript Beginner', 'Lorem ipsum dolor sit amet.', 15),
( 'LiveScript Advanced', 'Lorem ipsum dolor sit amet.', 10),
( 'LiveScript Master', 'Lorem ipsum dolor sit amet.', 10),
( 'LOGO Entry-level', 'Lorem ipsum dolor sit amet.', 15),
( 'LOGO Beginner', 'Lorem ipsum dolor sit amet.', 10),
( 'LOGO Advanced', 'Lorem ipsum dolor sit amet.', 10),
( 'LOGO Master', 'Lorem ipsum dolor sit amet.', 15),
( 'Lua Entry-level', 'Lorem ipsum dolor sit amet.', 20),
( 'Lua Beginner', 'Lorem ipsum dolor sit amet.', 15),
( 'Lua Advanced', 'Lorem ipsum dolor sit amet.', 10),
( 'Lua Master', 'Lorem ipsum dolor sit amet.', 10),
( 'MACLISP Entry-level', 'Lorem ipsum dolor sit amet.', 15),
( 'MACLISP Beginner', 'Lorem ipsum dolor sit amet.', 15),
( 'MACLISP Advanced', 'Lorem ipsum dolor sit amet.', 15),
( 'MACLISP Master', 'Lorem ipsum dolor sit amet.', 10),
( 'Matlab Entry-level', 'Lorem ipsum dolor sit amet.', 10),
( 'Matlab Beginner', 'Lorem ipsum dolor sit amet.', 15),
( 'Matlab Advanced', 'Lorem ipsum dolor sit amet.', 15),
( 'Matlab Master', 'Lorem ipsum dolor sit amet.', 20),
( 'MUMPS Entry-level', 'Lorem ipsum dolor sit amet.', 20),
( 'MUMPS Beginner', 'Lorem ipsum dolor sit amet.', 20),
( 'MUMPS Advanced', 'Lorem ipsum dolor sit amet.', 15),
( 'MUMPS Master', 'Lorem ipsum dolor sit amet.', 10),
( 'Objective-C Entry-level', 'Lorem ipsum dolor sit amet.', 15),
( 'Objective-C Beginner', 'Lorem ipsum dolor sit amet.', 10),
( 'Objective-C Advanced', 'Lorem ipsum dolor sit amet.', 20),
( 'Objective-C Master', 'Lorem ipsum dolor sit amet.', 10),
( 'OCaml Entry-level', 'Lorem ipsum dolor sit amet.', 10),
( 'OCaml Beginner', 'Lorem ipsum dolor sit amet.', 20),
( 'OCaml Advanced', 'Lorem ipsum dolor sit amet.', 10),
( 'OCaml Master', 'Lorem ipsum dolor sit amet.', 10),
( 'Pascal Entry-level', 'Lorem ipsum dolor sit amet.', 20),
( 'Pascal Beginner', 'Lorem ipsum dolor sit amet.', 15),
( 'Pascal Advanced', 'Lorem ipsum dolor sit amet.', 15),
( 'Pascal Master', 'Lorem ipsum dolor sit amet.', 20),
( 'Perl Entry-level', 'Lorem ipsum dolor sit amet.', 10),
( 'Perl Beginner', 'Lorem ipsum dolor sit amet.', 20),
( 'Perl Advanced', 'Lorem ipsum dolor sit amet.', 15),
( 'Perl Master', 'Lorem ipsum dolor sit amet.', 20),
( 'PHP Entry-level', 'Lorem ipsum dolor sit amet.', 20),
( 'PHP Beginner', 'Lorem ipsum dolor sit amet.', 15),
( 'PHP Advanced', 'Lorem ipsum dolor sit amet.', 20),
( 'PHP Master', 'Lorem ipsum dolor sit amet.', 15),
( 'PureBasic Entry-level', 'Lorem ipsum dolor sit amet.', 20),
( 'PureBasic Beginner', 'Lorem ipsum dolor sit amet.', 15),
( 'PureBasic Advanced', 'Lorem ipsum dolor sit amet.', 10),
( 'PureBasic Master', 'Lorem ipsum dolor sit amet.', 20),
( 'Python Entry-level', 'Lorem ipsum dolor sit amet.', 15),
( 'Python Beginner', 'Lorem ipsum dolor sit amet.', 15),
( 'Python Advanced', 'Lorem ipsum dolor sit amet.', 20),
( 'Python Master', 'Lorem ipsum dolor sit amet.', 10),
( 'Prolog Entry-level', 'Lorem ipsum dolor sit amet.', 15),
( 'Prolog Beginner', 'Lorem ipsum dolor sit amet.', 15),
( 'Prolog Advanced', 'Lorem ipsum dolor sit amet.', 20),
( 'Prolog Master', 'Lorem ipsum dolor sit amet.', 15),
( 'QBasic Entry-level', 'Lorem ipsum dolor sit amet.', 20),
( 'QBasic Beginner', 'Lorem ipsum dolor sit amet.', 10),
( 'QBasic Advanced', 'Lorem ipsum dolor sit amet.', 10),
( 'QBasic Master', 'Lorem ipsum dolor sit amet.', 20),
( 'R Entry-level', 'Lorem ipsum dolor sit amet.', 10),
( 'R Beginner', 'Lorem ipsum dolor sit amet.', 10),
( 'R Advanced', 'Lorem ipsum dolor sit amet.', 10),
( 'R Master', 'Lorem ipsum dolor sit amet.', 20),
( 'Reia Entry-level', 'Lorem ipsum dolor sit amet.', 15),
( 'Reia Beginner', 'Lorem ipsum dolor sit amet.', 15),
( 'Reia Advanced', 'Lorem ipsum dolor sit amet.', 20),
( 'Reia Master', 'Lorem ipsum dolor sit amet.', 20),
( 'Ruby Entry-level', 'Lorem ipsum dolor sit amet.', 20),
( 'Ruby Beginner', 'Lorem ipsum dolor sit amet.', 15),
( 'Ruby Advanced', 'Lorem ipsum dolor sit amet.', 10),
( 'Ruby Master', 'Lorem ipsum dolor sit amet.', 20),
( 'Rust Entry-level', 'Lorem ipsum dolor sit amet.', 10),
( 'Rust Beginner', 'Lorem ipsum dolor sit amet.', 15),
( 'Rust Advanced', 'Lorem ipsum dolor sit amet.', 15),
( 'Rust Master', 'Lorem ipsum dolor sit amet.', 20),
( 'Scala Entry-level', 'Lorem ipsum dolor sit amet.', 20),
( 'Scala Beginner', 'Lorem ipsum dolor sit amet.', 20),
( 'Scala Advanced', 'Lorem ipsum dolor sit amet.', 10),
( 'Scala Master', 'Lorem ipsum dolor sit amet.', 15),
( 'Security Entry-level', 'Lorem ipsum dolor sit amet.', 10),
( 'Security Beginner', 'Lorem ipsum dolor sit amet.', 20),
( 'Security Advanced', 'Lorem ipsum dolor sit amet.', 15),
( 'Security Master', 'Lorem ipsum dolor sit amet.', 20),
( 'SGML Entry-level', 'Lorem ipsum dolor sit amet.', 10),
( 'SGML Beginner', 'Lorem ipsum dolor sit amet.', 10),
( 'SGML Advanced', 'Lorem ipsum dolor sit amet.', 15),
( 'SGML Master', 'Lorem ipsum dolor sit amet.', 10),
( 'Simula Entry-level', 'Lorem ipsum dolor sit amet.', 20),
( 'Simula Beginner', 'Lorem ipsum dolor sit amet.', 15),
( 'Simula Advanced', 'Lorem ipsum dolor sit amet.', 10),
( 'Simula Master', 'Lorem ipsum dolor sit amet.', 20),
( 'SQL Entry-level', 'Lorem ipsum dolor sit amet.', 10),
( 'SQL Beginner', 'Lorem ipsum dolor sit amet.', 10),
( 'SQL Advanced', 'Lorem ipsum dolor sit amet.', 15),
( 'SQL Master', 'Lorem ipsum dolor sit amet.', 10),
( 'SQL injection Entry-level', 'Lorem ipsum dolor sit amet.', 20),
( 'SQL injection Beginner', 'Lorem ipsum dolor sit amet.', 10),
( 'SQL injection Advanced', 'Lorem ipsum dolor sit amet.', 10),
( 'SQL injection Master', 'Lorem ipsum dolor sit amet.', 20),
( 'StackOverflow Entry-level', 'Lorem ipsum dolor sit amet.', 20),
( 'StackOverflow Beginner', 'Lorem ipsum dolor sit amet.', 10),
( 'StackOverflow Advanced', 'Lorem ipsum dolor sit amet.', 15),
( 'StackOverflow Master', 'Lorem ipsum dolor sit amet.', 15),
( 'Stanford LISP Entry-level', 'Lorem ipsum dolor sit amet.', 10),
( 'Stanford LISP Beginner', 'Lorem ipsum dolor sit amet.', 10),
( 'Stanford LISP Advanced', 'Lorem ipsum dolor sit amet.', 10),
( 'Stanford LISP Master', 'Lorem ipsum dolor sit amet.', 10),
( 'Swift Entry-level', 'Lorem ipsum dolor sit amet.', 10),
( 'Swift Beginner', 'Lorem ipsum dolor sit amet.', 20),
( 'Swift Advanced', 'Lorem ipsum dolor sit amet.', 10),
( 'Swift Master', 'Lorem ipsum dolor sit amet.', 10),
( 'Turbo Pascal Entry-level', 'Lorem ipsum dolor sit amet.', 20),
( 'Turbo Pascal Beginner', 'Lorem ipsum dolor sit amet.', 10),
( 'Turbo Pascal Advanced', 'Lorem ipsum dolor sit amet.', 10),
( 'Turbo Pascal Master', 'Lorem ipsum dolor sit amet.', 15),
( 'True BASIC Entry-level', 'Lorem ipsum dolor sit amet.', 20),
( 'True BASIC Beginner', 'Lorem ipsum dolor sit amet.', 10),
( 'True BASIC Advanced', 'Lorem ipsum dolor sit amet.', 15),
( 'True BASIC Master', 'Lorem ipsum dolor sit amet.', 15),
( 'VHDL Entry-level', 'Lorem ipsum dolor sit amet.', 10),
( 'VHDL Beginner', 'Lorem ipsum dolor sit amet.', 20),
( 'VHDL Advanced', 'Lorem ipsum dolor sit amet.', 15),
( 'VHDL Master', 'Lorem ipsum dolor sit amet.', 15),
( 'Visual Basic Entry-level', 'Lorem ipsum dolor sit amet.', 20),
( 'Visual Basic Beginner', 'Lorem ipsum dolor sit amet.', 10),
( 'Visual Basic Advanced', 'Lorem ipsum dolor sit amet.', 20),
( 'Visual Basic Master', 'Lorem ipsum dolor sit amet.', 15),
( 'Visual FoxPro Entry-level', 'Lorem ipsum dolor sit amet.', 20),
( 'Visual FoxPro Beginner', 'Lorem ipsum dolor sit amet.', 15),
( 'Visual FoxPro Advanced', 'Lorem ipsum dolor sit amet.', 15),
( 'Visual FoxPro Master', 'Lorem ipsum dolor sit amet.', 15),
( 'WML Entry-level', 'Lorem ipsum dolor sit amet.', 20),
( 'WML Beginner', 'Lorem ipsum dolor sit amet.', 10),
( 'WML Advanced', 'Lorem ipsum dolor sit amet.', 20),
( 'WML Master', 'Lorem ipsum dolor sit amet.', 20),
( 'WHTML Entry-level', 'Lorem ipsum dolor sit amet.', 20),
( 'WHTML Beginner', 'Lorem ipsum dolor sit amet.', 20),
( 'WHTML Advanced', 'Lorem ipsum dolor sit amet.', 10),
( 'WHTML Master', 'Lorem ipsum dolor sit amet.', 20),
( 'XLISP Entry-level', 'Lorem ipsum dolor sit amet.', 10),
( 'XLISP Beginner', 'Lorem ipsum dolor sit amet.', 20),
( 'XLISP Advanced', 'Lorem ipsum dolor sit amet.', 15),
( 'XLISP Master', 'Lorem ipsum dolor sit amet.', 20),
( 'XML Entry-level', 'Lorem ipsum dolor sit amet.', 10),
( 'XML Beginner', 'Lorem ipsum dolor sit amet.', 20),
( 'XML Advanced', 'Lorem ipsum dolor sit amet.', 10),
( 'XML Master', 'Lorem ipsum dolor sit amet.', 10),
( 'XSS Entry-level', 'Lorem ipsum dolor sit amet.', 10),
( 'XSS Beginner', 'Lorem ipsum dolor sit amet.', 10),
( 'XSS Advanced', 'Lorem ipsum dolor sit amet.', 15),
( 'XSS Master', 'Lorem ipsum dolor sit amet.', 10),
( 'YAML Entry-level', 'Lorem ipsum dolor sit amet.', 20),
( 'YAML Beginner', 'Lorem ipsum dolor sit amet.', 15),
( 'YAML Advanced', 'Lorem ipsum dolor sit amet.', 20),
( 'YAML Master', 'Lorem ipsum dolor sit amet.', 10),
( 'ZetaLisp Entry-level', 'Lorem ipsum dolor sit amet.', 10),
( 'ZetaLisp Beginner', 'Lorem ipsum dolor sit amet.', 10),
( 'ZetaLisp Advanced', 'Lorem ipsum dolor sit amet.', 15),
( 'ZetaLisp Master', 'Lorem ipsum dolor sit amet.', 10),
